-- Tasks & meetings (follow-ups, reminders on entities).
-- Idempotent for manual runs when not using TypeORM synchronize.
-- MySQL 8+

CREATE TABLE IF NOT EXISTS `tasks` (
  `id` char(36) NOT NULL,
  `firm_id` char(36) DEFAULT NULL,
  `created_by` char(36) NOT NULL,
  `assignee_id` char(36) DEFAULT NULL,
  `matter_id` char(36) DEFAULT NULL,
  `client_id` char(36) DEFAULT NULL,
  `daily_listing_id` char(36) DEFAULT NULL,
  `title` varchar(500) NOT NULL,
  `description` text,
  `kind` enum('task','follow_up') NOT NULL DEFAULT 'task',
  `status` enum('pending','in_progress','done','cancelled') NOT NULL DEFAULT 'pending',
  `due_at` datetime DEFAULT NULL,
  `reminder_at` datetime DEFAULT NULL,
  `reminder_sent_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `IDX_tasks_firm_id` (`firm_id`),
  KEY `IDX_tasks_matter_id` (`matter_id`),
  KEY `IDX_tasks_client_id` (`client_id`),
  KEY `IDX_tasks_due_at` (`due_at`),
  KEY `IDX_tasks_reminder_at` (`reminder_at`),
  CONSTRAINT `FK_tasks_firm` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_tasks_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_tasks_assignee` FOREIGN KEY (`assignee_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_tasks_matter` FOREIGN KEY (`matter_id`) REFERENCES `matters` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_tasks_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_tasks_daily_listing` FOREIGN KEY (`daily_listing_id`) REFERENCES `daily_listings` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `meetings` (
  `id` char(36) NOT NULL,
  `firm_id` char(36) DEFAULT NULL,
  `created_by` char(36) NOT NULL,
  `organizer_id` char(36) DEFAULT NULL,
  `matter_id` char(36) DEFAULT NULL,
  `client_id` char(36) DEFAULT NULL,
  `daily_listing_id` char(36) DEFAULT NULL,
  `title` varchar(500) NOT NULL,
  `description` text,
  `location` varchar(500) DEFAULT NULL,
  `meeting_url` varchar(1024) DEFAULT NULL,
  `meeting_link_provider` enum('google_meet','microsoft_teams','zoom','other') DEFAULT NULL,
  `share_link_with_client` tinyint(1) NOT NULL DEFAULT 1,
  `start_at` datetime NOT NULL,
  `end_at` datetime DEFAULT NULL,
  `status` enum('scheduled','completed','cancelled') NOT NULL DEFAULT 'scheduled',
  `reminder_at` datetime DEFAULT NULL,
  `reminder_sent_at` datetime DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `IDX_meetings_firm_id` (`firm_id`),
  KEY `IDX_meetings_matter_id` (`matter_id`),
  KEY `IDX_meetings_client_id` (`client_id`),
  KEY `IDX_meetings_start_at` (`start_at`),
  KEY `IDX_meetings_reminder_at` (`reminder_at`),
  CONSTRAINT `FK_meetings_firm` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_meetings_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_meetings_organizer` FOREIGN KEY (`organizer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_meetings_matter` FOREIGN KEY (`matter_id`) REFERENCES `matters` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_meetings_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_meetings_daily_listing` FOREIGN KEY (`daily_listing_id`) REFERENCES `daily_listings` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
